routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'questions', 'as'=>'question.'], function () {
  Route::get('/', 'QuestionController@index')->name('index');
  Route::get('/show/{question}', 'QuestionController@show')->name('show');
  Route::post('/store', 'QuestionController@store')->name('store');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::delete('delete/{question}','QuestionController@destroy')->name('delete');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::patch('update/{question}', 'QuestionController@update')->name('update');
});

Route::group(['prefix'=>'categories', 'as'=>'category.'], function () {
  Route::get('/', 'CategoryController@index')->name('index');
  Route::post('store', 'CategoryController@store')->name('store');
  Route::get('edit/{category}', 'CategoryController@edit')->name('edit');
  Route::patch('update/{category}', 'CategoryController@update')->name('update');
  Route::delete('delete/{category}','CategoryController@destroy')->name('delete');
  Route::get('create', 'CategoryController@create')->name('create');
  Route::get('show/{category}', 'CategoryController@show')->name('show');
  Route::get('download/{category}', 'CategoryController@download')->name('download');
});

Route::group(['prefix'=>'answers', 'as'=>'answer.'], function () {
  Route::get('/', 'AnswerController@index')->name('index');
  Route::get('show/{answer}', 'AnswerController@show')->name('show');
  Route::get('edit/{answer}', 'AnswerController@edit')->name('edit');
  Route::delete('delete/{answer}','AnswerController@destroy')->name('delete');
  Route::patch('update/{answer}', 'AnswerController@update')->name('update');
});

Route::group(['prefix'=>'words', 'as'=>'word.'], function () {
  Route::get('/show', 'WordController@show')->name('show');
  Route::get('/extractor', 'WordController@extractor')->name('extract');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = [
        'text',
        'persian_text',
        'incorrect_text',
        'persian_incorrect_text',
        'is_reviewed'
    ];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function answers(){
        return $this->hasMany('App\Answer');
    }
}

app/Http/Controllers/API/QuestionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::where('is_translated', null)->limit(10)->get();
        return $questions;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        return $question->load('answers');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
    }

    /**
     * Generate random questions for given categories
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function random (Request $request) {
        $categories = json_decode($request->input('categories'),true);
        $questionQuantity = $request->input('questionQuantity');
        $questions = Question::whereIn('category_id', $categories)
                        ->with('answers')
                        ->inRandomOrder()
                        ->limit($questionQuantity)
                        ->get();
        return response($questions);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::with('category')->Paginate(10);
        return view('question.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'questions' => 'bail|required',
            'category' => 'bail|required',
        ],
        [
            'questions.required' => 'A list of questions is required',
            'category.required' => 'A category is required'
        ]);

        $questions = json_decode($request->file('questions')->get());

        if (!isset($questions[0]->question)) {
            foreach ($questions as $key => $question) {
                $questionModel = new Question;
                $questionModel->category_id = $request->category;
                $questionModel->question_number = $key + 1;

                if (isset($question->image)) {
                    $url = $question->image_src;
                    $info = pathinfo($url);
                    Storage::makeDirectory('public/images');

                    $imageName = $info['filename'];

                    $image_resize = Image::make(file_get_contents($url));
                    $image_resize->save(public_path('storage/images/'.$imageName.'.jpg'));
                    $questionModel->image = $imageName.'.jpg';
                    $questionModel->image_src = $url;
                }

                $questionModel->text = $question->text;
                $questionModel->correct_answer = $question->correct_answer;
                $questionModel->incorrect_text = $question->incorrect_text;
                $questionModel->persian_text = $question->persian_text;
                $questionModel->persian_incorrect_text = $question->persian_incorrect_text;
                $questionModel->is_reviewed = $question->is_reviewed;

                $questionModel->save();

                $answers = $question->answers;
                foreach ($answers as $key => $answer) {
                    $answerModel = new Answer;
                    $answerModel->question_id = $questionModel->id;
                    $answerModel->text = $answer->text;
                    $answerModel->persian_text = $answer->persian_text;
                    $answerModel->answer_number = $answer->answer_number;
                    $answerModel->is_answer = (int) $answer->is_answer;
                    $answerModel->is_reviewed = (int) $answer->is_reviewed;
                    $answerModel->save();
                }
            }
        } else {
            foreach ($questions as $key => $question) {
                $questionModel = new Question;
                $questionModel->category_id = $request->category;
                $questionModel->question_number = $key + 1;

                if (isset($question->image)) {
                    $url = $question->image;
                    $info = pathinfo($url);
                    Storage::makeDirectory('public/images');

                    $imageName = $info['filename'];

                    $image_resize = Image::make(file_get_contents($url));
                    $image_resize->save(public_path('storage/images/'.$imageName.'.jpg'));
                    $questionModel->image = $imageName.'.jpg';
                    $questionModel->image_src = $url;
                }

                $questionModel->text = $question->question;
                $questionModel->correct_answer = $question->correctAnswer;
                $questionModel->incorrect_text = $question->incorrectText;
                $questionModel->persian_text = $question->persianText;

                if (isset($question->persianIncorrectText)) {
                    $questionModel->persian_incorrect_text = $question->persianIncorrectText;
                }

                $questionModel->save();

                $answers = $question->answers;
                foreach ($answers as $key => $answer) {
                    $answerModel = new Answer;
                    $answerModel->question_id = $questionModel->id;
                    $answerModel->text = $answer->answer;
                    $answerModel->persian_text = $answer->persianText;
                    $answerModel->answer_number = $answer->answerNumber;
                    $answerModel->is_answer = (int) $answer->isCorrect;
                    $answerModel->save();
                }
            }
        }

        return redirect()->route('home')->with('message', 'Questions uploaded');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        return view('question.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        return view('question.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $request->validate([
            'text' => 'bail|required|max:255',
            'persian_text' => 'bail|required|max:255'
        ]);

        $question->update($request->all());

        return redirect()->route('question.show', $question)->with('message', 'Question updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $question->delete();
        return redirect()->route('question.index')->with('message', 'Question deleted');
    }
}

resources/views/question/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('question.update', $question) }}" method="post">
                        @csrf
                        @method('patch')
                        <table class="table table-borderless">
                            <tbody>
                                <tr>
                                    <td class="font-weight-bold text-uppercase">ID</td>
                                    <td>{{ $question->id }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">English text:</td>
                                    <td>
                                        <input class="form-control" type="text" name="text" value="{{ $question->text }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Persian text:</td>
                                    <td>
                                        <input class="form-control" type="text" dir="rtl" name="persian_text" value="{{ $question->persian_text }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Category:</td>
                                    <td>{{ $question->category->name }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Correct answer:</td>
                                    <td>{{ $question->correct_answer }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Is reviewed:</td>
                                    <td>
                                        <switch-component :disabled="false" :state="{{ $question->is_reviewed }}"></switch-component>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Incorrect text:</td>
                                    <td>
                                        <textarea class="form-control" rows="3" name="incorrect_text" id="incorrect_text">{{ $question->incorrect_text }}</textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Persian incorrect text:</td>
                                    <td>
                                        <textarea
                                        	class="form-control"
                                        	rows="3"
                                        	dir="rtl"
                                        	name="persian_incorrect_text"
                                        	id="persian_incorrect_text">{{ $question->persian_incorrect_text }}</textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Answers:</td>
                                    <td>
                                        <table class="table table-bordered table-striped">
	                                        <thead>
	                                            <tr>
	                                                <th>#</th>
	                                                <th class="text-uppercase">English text</th>
	                                                <th class="text-right text-uppercase">Persian text</th>
	                                                <th class="text-right text-uppercase">Is correct</th>
                                                    <th class="text-right text-uppercase">Is reviewed</th>
	                                                <th></th>
	                                            </tr>
	                                        </thead>
	                                        <tbody>
	                                            @foreach($question->answers as $answer)
	                                                <tr>
	                                                    <td>{{ $answer->answer_number }}</td>
	                                                    <td>{{ $answer->text }}</td>
	                                                    <td class="text-right">{{ $answer->persian_text }}</td>
	                                                    <td class="text-center">
	                                                        @if($answer->is_answer)
	                                                            <i style="color: green" class="fas fa-check"></i>
	                                                        @endif
	                                                    </td>
                                                        <td class="text-center">
                                                            @if($answer->is_reviewed)
                                                                <i style="color: green" class="fas fa-check"></i>
                                                            @else
                                                                <i style="color: red" class="fas fa-times"></i>
                                                            @endif
                                                        </td>
	                                                    <td class="text-right">
	                                                        <a href="{{ route('answer.edit', $answer) }}" type="button" class="btn btn-secondary">Edit</a>
	                                                    </td>
	                                                </tr>
	                                            @endforeach
	                                        </tbody>
	                                    </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/question/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Questions</div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Question</th>
                                <th>Category</th>
                                <th>Translated</th>
                                <th>Reviewed</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($questions as $question)
                                <tr>
                                    <td>{{ $question->id }}</td>
                                    <td>{{ $question->text }}</td>
                                    <td>{{ $question->category->name }}</td>
                                    <td style="text-align: center">
                                        @if($question->persian_text)
                                            <i style="color: green" class="fas fa-check"></i>
                                        @else
                                            <i style="color: red" class="fas fa-times"></i>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($question->is_reviewed)
                                            <i style="color: green" class="fas fa-check"></i>
                                        @else
                                            <i style="color: red" class="fas fa-times"></i>
                                        @endif
                                    </td>
                                    <td>
                                        <a type="button" href="{{ route('question.show', $question) }}" style="color: white;" class="btn btn-secondary">View</a>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                    {{ $questions->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/question/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-borderless">
                        <tbody>
                            <tr >
                                <td class="font-weight-bold">ID</td>
                                <td>{{ $question->id }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">English text:</td>
                                <td>{{ $question->text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Persian text:</td>
                                <td>{{ $question->persian_text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Category:</td>
                                <td>{{ $question->category->name }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold text-nowrap">Correct answer number:</td>
                                <td>{{ $question->correct_answer }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Is reviewed:</td>
                                <td>
                                    <switch-component :disabled="true" :state="{{ $question->is_reviewed }}"></switch-component>
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Incorrect text:</td>
                                <td>{{ $question->incorrect_text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold text-nowrap">Persian incorrect text:</td>
                                <td>{{ $question->persian_incorrect_text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Answers:</td>
                                <td>
                                    <table class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th class="text-uppercase">English text:</th>
                                                <th class="text-right text-uppercase">Persian Text</th>
                                                <th class="text-center text-uppercase">Is Correct</th>
                                                <th class="text-center text-uppercase">Is reviewed</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($question->answers as $answer)
                                                <tr>
                                                    <td>{{ $answer->answer_number }}</td>
                                                    <td>{{ $answer->text }}</td>
                                                    <td class="text-right">{{ $answer->persian_text }}</td>
                                                    <td class="text-center">
                                                        @if($answer->is_answer)
                                                            <i style="color: green" class="fas fa-check"></i>
                                                        @endif
                                                    </td>
                                                    <td class="text-center">
                                                        @if($answer->is_reviewed)
                                                            <i style="color: green" class="fas fa-check"></i>
                                                        @else
                                                            <i style="color: red" class="fas fa-times"></i>
                                                        @endif
                                                    </td>
                                                    <td class="text-right">
                                                        <a href="{{ route('answer.show', $answer) }}" type="button" class="btn btn-primary">View</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <form action="{{ route('question.delete', $question) }}" method="post">
                    <a href="{{ route('question.edit', $question) }}" type="button" class="btn btn-secondary">Edit</a>
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection