routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'questions', 'as'=>'question.'], function () {
  Route::get('/', 'QuestionController@index')->name('index');
  Route::get('/show/{question}', 'QuestionController@show')->name('show');
  Route::post('/store', 'QuestionController@store')->name('store');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::delete('delete/{question}','QuestionController@destroy')->name('delete');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::patch('update/{question}', 'QuestionController@update')->name('update');
});

Route::group(['prefix'=>'categories', 'as'=>'category.'], function () {
  Route::get('/', 'CategoryController@index')->name('index');
  Route::post('store', 'CategoryController@store')->name('store');
  Route::get('edit/{category}', 'CategoryController@edit')->name('edit');
  Route::patch('update/{category}', 'CategoryController@update')->name('update');
  Route::delete('delete/{category}','CategoryController@destroy')->name('delete');
  Route::get('create', 'CategoryController@create')->name('create');
  Route::get('show/{category}', 'CategoryController@show')->name('show');
  Route::get('download/{category}', 'CategoryController@download')->name('download');
});

Route::group(['prefix'=>'answers', 'as'=>'answer.'], function () {
  Route::get('/', 'AnswerController@index')->name('index');
  Route::get('show/{answer}', 'AnswerController@show')->name('show');
  Route::get('edit/{answer}', 'AnswerController@edit')->name('edit');
  Route::delete('delete/{answer}','AnswerController@destroy')->name('delete');
  Route::patch('update/{answer}', 'AnswerController@update')->name('update');
});

Route::group(['prefix'=>'words', 'as'=>'word.'], function () {
  Route::get('/show', 'WordController@show')->name('show');
  Route::get('/extractor', 'WordController@extractor')->name('extract');
});

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
	protected $fillable = [
		'text',
		'persian_text',
    'is_reviewed'
	];

	public function question(){
		return $this->belongsTo('App\Question');
	}
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $answers = Answer::with('question')->Paginate(10);
        return view('answer.index', compact('answers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  Answer $answer
     * @return \Illuminate\Http\Response
     */
    public function show(Answer $answer)
    {
        $relatedAnswers = Answer::where('question_id', $answer->question->id)->where('id', '!=', $answer->id)->get();
        return view('answer.show', compact('answer', 'relatedAnswers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Answer $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Answer $answer)
    {
        $relatedAnswers = Answer::where('question_id', $answer->question->id)->where('id', '!=', $answer->id)->get();
        return view('answer.edit', compact('answer', 'relatedAnswers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Answer $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Answer $answer)
    {
        $request->validate([
            'text' => 'bail|required|max:255',
            'persian_text' => 'bail|required|max:255'
        ],
        [
            'text.required' => 'English text field cannot be empty',
            'persian_text.required' => 'Persian text field cannot be empty'
        ]);

        $answer->update($request->all());

        return redirect()->route('answer.show', $answer)->with('message', 'Answer updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Answer $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Answer $answer)
    {
        $question->delete();
        return redirect()->route('answer.index')->with('message', 'Answer deleted');
    }
}

resources/views/answer/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('answer.update', $answer) }}" method="post">
                        @csrf
                        @method('patch')
                        <table class="table table-borderless">
                            <tbody>
                                <tr >
                                    <td class="font-weight-bold">ID:</td>
                                    <td>{{ $answer->id }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Answer number:</td>
                                    <td>{{ $answer->answer_number }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Is reviewed:</td>
                                    <td>
                                        <switch-component :disabled="false" :state="{{ $answer->is_reviewed }}"></switch-component>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Correct answer:</td>
                                    <td>{{ $answer->is_answer }}</td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">English text:</td>
                                    <td>
                                        <input class="form-control" type="text" name="text" value="{{ $answer->text }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold">Persian text:</td>
                                    <td>
                                        <input class="form-control" dir="rtl" type="text" name="persian_text" value="{{ $answer->persian_text }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold text-nowrap">Related answers:</td>
                                    <td>
                                        <table class="table table-bordered table-striped">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th class="text-uppercase">English Text</th>
                                                    <th class="text-right text-uppercase">Persian Text</th>
                                                    <th class="text-right text-uppercase">Is Correct</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($relatedAnswers as $answer)
                                                    <tr>
                                                        <td>{{ $answer->answer_number }}</td>
                                                        <td>{{ $answer->text }}</td>
                                                        <td class="text-right">{{ $answer->persian_text }}</td>
                                                        <td class="text-right">
                                                            @if($answer->is_answer)
                                                                <i style="color: green" class="fas fa-check"></i>
                                                            @endif
                                                        </td>
                                                        <td class="text-right">
                                                            <a href="{{ route('answer.edit', $answer) }}" type="button" class="btn btn-secondary">Edit</a>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="font-weight-bold text-nowrap">Answer's question:</td>
                                    <td>
                                        <table class="table table-bordered table-striped">
                                            <tbody>
                                                <tr >
                                                    <td>ID:</td>
                                                    <td>{{ $answer->question->id }}</td>
                                                </tr>
                                                <tr>
                                                    <td>English text:</td>
                                                    <td>{{ $answer->question->text }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Persian text:</td>
                                                    <td>{{ $answer->question->persian_text }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Category:</td>
                                                    <td>{{ $answer->question->category->name }}</td>
                                                </tr>
                                                <tr>
                                                    <td>Incorrect text:</td>
                                                    <td>{{ $answer->question->incorrect_text }}</td>
                                                </tr>
                                                <tr>
                                                    <td class="text-nowrap">Persian incorrect text</td>
                                                    <td>{{ $answer->question->persian_incorrect_text }}</td>
                                                </tr>
                                                <tr>
                                                    <td ></td>
                                                    <td class="text-right">
                                                        <a href="{{ route('question.edit', $answer->question) }}" type="button" class="btn btn-secondary">Edit</a>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-secondary">Update</button>
                        <form action="{{ route('answer.delete', $answer) }}" method="post">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/answer/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Answers</div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Answer</th>
                                <th class="text-right">Persian Text</th>
                                <th class="text-right">Reviewed</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($answers as $answer)

                                <tr>
                                    <td>{{ $answer->id }}</td>
                                    <td>{{ $answer->text }}</td>
                                    <td class="text-right">{{ $answer->persian_text }}</td>
                                    <td class="text-center">
                                        @if($answer->is_reviewed)
                                            <i style="color: green" class="fas fa-check"></i>
                                        @else
                                            <i style="color: red" class="fas fa-times"></i>
                                        @endif
                                    </td>
                                    <td class="text-right">
                                        <a type="button" href="{{ route('answer.show', $answer) }}" style="color: white;" class="btn btn-secondary">View</a>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                    {{ $answers->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/answer/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-borderless">
                        <tbody>
                            <tr >
                                <td class="font-weight-bold">ID:</td>
                                <td>{{ $answer->id }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Answer #:</td>
                                <td>{{ $answer->answer_number }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Correct answer:</td>
                                <td>
                                    @if($answer->is_answer)
                                        <i style="color: green" class="fas fa-check"></i>
                                    @else
                                        <i style="color: red" class="fas fa-times"></i>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Is reviewed:</td>
                                <td>
                                    <switch-component :disabled="true" :state="{{ $answer->is_reviewed }}"></switch-component>
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">English text:</td>
                                <td>{{ $answer->text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Persian text:</td>
                                <td>{{ $answer->persian_text }}</td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold text-nowrap">Related answers:</td>
                                <td>
                                    <table class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th class="text-nowrap text-uppercase">English Text</th>
                                                <th class="text-nowrap text-right text-uppercase">Persian Text</th>
                                                <th class="text-nowrap text-center text-uppercase">Is Correct</th>
                                                <th class="text-nowrap text-center text-uppercase">Is reviewed</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($relatedAnswers as $relatedAnswer)
                                                <tr>
                                                    <td>{{ $relatedAnswer->answer_number }}</td>
                                                    <td>{{ $relatedAnswer->text }}</td>
                                                    <td class="text-right">{{ $relatedAnswer->persian_text }}</td>
                                                    <td class="text-center">
                                                        @if($relatedAnswer->is_answer)
                                                            <i style="color: green" class="fas fa-check"></i>
                                                        @endif
                                                    </td>
                                                    <td class="text-center">
                                                        @if($relatedAnswer->is_reviewed)
                                                            <i style="color: green" class="fas fa-check"></i>
                                                        @else
                                                            <i style="color: red" class="fas fa-times"></i>
                                                        @endif
                                                    </td>
                                                    <td class="text-right">
                                                        <a href="{{ route('answer.show', $relatedAnswer) }}" type="button" class="btn btn-primary">View</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold text-nowrap">Answer's question:</td>
                                <td>
                                    <table class="table table-bordered table-striped">
                                        <tbody>
                                            <tr >
                                                <td>ID:</td>
                                                <td>{{ $answer->question->id }}</td>
                                            </tr>
                                            <tr>
                                                <td>English text:</td>
                                                <td>{{ $answer->question->text }}</td>
                                            </tr>
                                            <tr>
                                                <td>Persian text:</td>
                                                <td>{{ $answer->question->persian_text }}</td>
                                            </tr>
                                            <tr>
                                                <td>Category:</td>
                                                <td>{{ $answer->question->category->name }}</td>
                                            </tr>
                                            <tr>
                                                <td>Incorrect text:</td>
                                                <td>{{ $answer->question->incorrect_text }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-nowrap">Persian incorrect text</td>
                                                <td>{{ $answer->question->persian_incorrect_text }}</td>
                                            </tr>
                                            <tr>
                                                <td ></td>
                                                <td class="text-right">
                                                    <a href="{{ route('question.show', $answer->question) }}" type="button" class="btn btn-primary">View</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <form action="{{ route('answer.delete', $answer) }}" method="post">
                    <a href="{{ route('answer.edit', $answer) }}" type="button" class="btn btn-secondary">Edit</a>
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection