routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'questions', 'as'=>'question.'], function () {
  Route::get('/', 'QuestionController@index')->name('index');
  Route::get('/show/{question}', 'QuestionController@show')->name('show');
  Route::post('/store', 'QuestionController@store')->name('store');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::delete('delete/{question}','QuestionController@destroy')->name('delete');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::patch('update/{question}', 'QuestionController@update')->name('update');
});

Route::group(['prefix'=>'categories', 'as'=>'category.'], function () {
  Route::get('/', 'CategoryController@index')->name('index');
  Route::post('store', 'CategoryController@store')->name('store');
  Route::get('edit/{category}', 'CategoryController@edit')->name('edit');
  Route::patch('update/{category}', 'CategoryController@update')->name('update');
  Route::delete('delete/{category}','CategoryController@destroy')->name('delete');
  Route::get('create', 'CategoryController@create')->name('create');
  Route::get('show/{category}', 'CategoryController@show')->name('show');
  Route::get('download/{category}', 'CategoryController@download')->name('download');
});

Route::group(['prefix'=>'answers', 'as'=>'answer.'], function () {
  Route::get('/', 'AnswerController@index')->name('index');
  Route::get('show/{answer}', 'AnswerController@show')->name('show');
  Route::get('edit/{answer}', 'AnswerController@edit')->name('edit');
  Route::delete('delete/{answer}','AnswerController@destroy')->name('delete');
  Route::patch('update/{answer}', 'AnswerController@update')->name('update');
});

Route::group(['prefix'=>'words', 'as'=>'word.'], function () {
  Route::get('/show', 'WordController@show')->name('show');
  Route::get('/extractor', 'WordController@extractor')->name('extract');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name',
        'persian_name'
    ];

    public function categories(){
        return $this->belongsToMany('App\Question');
    }

    public function questions()
    {
        return $this->hasMany('App\Question');
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Category::withCount('questions')->get();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return $category->with('questions.answers')->first();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Question;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'bail|required|unique:categories|max:255',
        ],
        [
            'name.unique' => 'Category already exists'
        ]);

        Category::create(['name' => $request->name]);

        return redirect()->route('category.index')->with('message', 'New category created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category, Request $request)
    {
        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'bail|required',
            'persian_name' => 'bail|required'
        ]);

        $category->update($request->all());

        return redirect()->route('category.show', $category)->with('message', 'Category updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index')->with('message', 'Category deleted');
    }


    /**
     * Download category as a json file
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function download(Category $category){
        $questions = Question::where('category_id', $category->id)->with('answers', 'category')->get();
        $filename = $category->name.".json";
        $handle = fopen($filename, 'w+');
        fputs($handle, $questions->toJson(JSON_PRETTY_PRINT));
        fclose($handle);
        $headers = array('Content-type'=> 'application/json');
        return response()->download($filename, $category->name.'.json',$headers);
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-header">Create new category</div>
                <div class="card-body">
                    <form action="{{ route('category.store') }}" method="post">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="name" placeholder="New category name">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-header">Edit category</div>
                <div class="card-body">
                    <form action="{{ route('category.update', $category) }}" method="post">
                        @csrf
                        @method('PATCH')
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="name" value="{{ $category->name }}">
                        </div>
                        <div class="input-group mb-3">
                            <input type="text" dir="rtl" class="form-control" name="persian_name" value="{{ $category->persian_name }}">
                        </div>
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <ul class="list-group mb-3">
                        @foreach ($categories as $category)
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ $category->name }}
                                <span class="badge badge-primary badge-pill">{{ count($category->questions) }} {{"Questions"}}</span>
                                {{ $category->persian_name }}
                                <div class="btn-group">
                                    <a href="{{ route('category.show', $category) }}" type="button" class="btn btn-secondary">View</a>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                    <a href="{{ route('category.create') }}" type="button" class="btn btn-primary">New category</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <ul class="list-group mb-3">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ $category->name }}
                            <span>{{ $category->persian_name }}</span>
                            <div class="btn-group">
                                    <a href="{{ route('category.edit', $category) }}" type="button" class="btn btn-secondary">Edit</a>
                                    <a href="{{ route('category.download', $category) }}" type="button" class="btn btn-secondary">Download</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h4>{{ count($category->questions)}} Questions</h4></div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Question</th>
                                <th>Translated</th>
                                <th>Reviewed</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($category->questions as $question)
                                <tr>
                                    <td>{{ $question->id }}</td>
                                    <td>{{ $question->text }}</td>
                                    <td style="text-align: center">
                                        @if($question->persian_text)
                                            <i style="color: green" class="fas fa-check"></i>
                                        @else
                                            <i style="color: red" class="fas fa-times"></i>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($question->is_reviewed)
                                            <i style="color: green" class="fas fa-check"></i>
                                        @else
                                            <i style="color: red" class="fas fa-times"></i>
                                        @endif
                                    </td>
                                    <td>
                                        <a type="button" href="{{ route('question.show', $question) }}" style="color: white;" class="btn btn-secondary">View</a>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection