routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'questions', 'as'=>'question.'], function () {
  Route::get('/', 'QuestionController@index')->name('index');
  Route::get('/show/{question}', 'QuestionController@show')->name('show');
  Route::post('/store', 'QuestionController@store')->name('store');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::delete('delete/{question}','QuestionController@destroy')->name('delete');
  Route::get('edit/{question}', 'QuestionController@edit')->name('edit');
  Route::patch('update/{question}', 'QuestionController@update')->name('update');
});

Route::group(['prefix'=>'categories', 'as'=>'category.'], function () {
  Route::get('/', 'CategoryController@index')->name('index');
  Route::post('store', 'CategoryController@store')->name('store');
  Route::get('edit/{category}', 'CategoryController@edit')->name('edit');
  Route::patch('update/{category}', 'CategoryController@update')->name('update');
  Route::delete('delete/{category}','CategoryController@destroy')->name('delete');
  Route::get('create', 'CategoryController@create')->name('create');
  Route::get('show/{category}', 'CategoryController@show')->name('show');
  Route::get('download/{category}', 'CategoryController@download')->name('download');
});

Route::group(['prefix'=>'answers', 'as'=>'answer.'], function () {
  Route::get('/', 'AnswerController@index')->name('index');
  Route::get('show/{answer}', 'AnswerController@show')->name('show');
  Route::get('edit/{answer}', 'AnswerController@edit')->name('edit');
  Route::delete('delete/{answer}','AnswerController@destroy')->name('delete');
  Route::patch('update/{answer}', 'AnswerController@update')->name('update');
});

Route::group(['prefix'=>'words', 'as'=>'word.'], function () {
  Route::get('/show', 'WordController@show')->name('show');
  Route::get('/extractor', 'WordController@extractor')->name('extract');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @if (Auth::check())
                        <ul class="navbar-nav mr-auto">
                            <li><a class="nav-link" href="{{ route('category.index') }}">Categories</a></li>
                            <li><a class="nav-link" href="{{ route('question.index') }}">Questions</a></li>
                            <li><a class="nav-link" href="{{ route('answer.index') }}">Answers</a></li>
                        </ul>
                    @endif
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>
                        @elseif ($errors->any())
                            <div class="alert alert-danger">
                                {{ $errors->first() }}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
            @yield('content')
        </main>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    @stack('scripts')
</body>
</html>